// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstDemo.Data.Models.Data.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string AddressText { get; set; }

    public int? TownId { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Town Town { get; set; }
}